### PR TITLE
F90 detection

### LINKED ISSUE #4: Fortran 90 support checks
For systems with no gfortran (g77 or the like) the configuration runs through but for obvious reasons the build fails. so we need include some logic at main level that ensures f90 capabilities are present or fail otherwise. cmake already does that check - we just need to see what variable is pre-set for f90 caps. as we dont need fortran for zinc this should also be made iron-dependent.

### PR DESCRIPTION
**Pull request by rondiplomatico**
This closes #4.

### CODE REVIEW

**Comment by rondiplomatico** [comment]
any comments?

**Comment by hsorby** [comment]
Is it a necessity for HDF5 to have a fortran compiler to build? or just a possibility?

**Comment by rondiplomatico** [comment]
Jenkins-Builder: Can one of the admins verify this patch?

**Comment by rondiplomatico** [comment]
gojenkins!

**Pull request merged**
